### PR TITLE
Added support for Ruby

### PR DESCRIPTION
**Pull request by Beyarz**

### CODE REVIEW

**Comment by ro-tex** [comment]
Hi @Beyarz , looks good to me!

My only question is why would the caller need to specify a name for the file they are trying to download? That information is already included in the Skyfile.

**Comment by Beyarz** [comment]
> For the code example to work properly you need to include ruby syntax highlighting as we did with other languages here https://github.com/NebulousLabs/skynet-webportal/blob/master/src/components/CodeExamples/CodeExamples.js#L10-L13 and include it in the code tabs as other languages are https://github.com/NebulousLabs/skynet-webportal/blob/master/src/components/CodeExamples/CodeExamples.js#L21-L64

Done

**Comment by Beyarz** [comment]
What's left before you merge this?

**Comment by DavidVorick** [comment]
Hey, we really appreciate you making a third party SDK supporting Skynet in the form of ruby. Unfortunately, we have a few requirements for SDKs that get listed on the homepage, and so we can't include ruby. Chief reasons:

1. We don't control the repo. If you (or someone else adding their own SDK) were to add malicious code at some point, we would be sending our users to that code from the homepage.

2. We want all of our homepage SDKs to maintain feature parity. As we are adding features to Skynet rapidly, this means that every time we update our SDKs, we need to update all of them. We don't control third party SDKs,  which means we can't ensure they support all new features in a timely manner.

We're happy to tell the world about your ruby SDK over our social media channels though - discord, twitter, potentially the mailing list, if you would prefer that?

**Comment by Beyarz** [comment]
> 1. We don't control the repo. If you (or someone else adding their own SDK) were to add malicious code at some point, we would be sending our users to that code from the homepage.
> 2. We want all of our homepage SDKs to maintain feature parity. As we are adding features to Skynet rapidly, this means that every time we update our SDKs, we need to update all of them. We don't control third party SDKs,  which means we can't ensure they support all new features in a timely manner.
I wouldn't mind transferring the ownership to you guys.

> We're happy to tell the world about your ruby SDK over our social media channels though - discord, twitter, potentially the mailing list, if you would prefer that?
 If you aren't interested in my offer then I would be honoured if you informed the community about the sdk for Ruby devs! Hopefully that will attract some people who could potentially work on some improvements.

**Comment by DavidVorick** [comment]
> If you aren't interested in my offer then I would be honoured if you informed the community about the sdk for Ruby devs! Hopefully that will attract some people who could potentially work on some improvements.

For the time being let's go the community route. If you are ready, we can announce on Reddit and Discord

**Comment by Beyarz** [comment]
> > If you aren't interested in my offer then I would be honoured if you informed the community about the sdk for Ruby devs! Hopefully that will attract some people who could potentially work on some improvements.
> 
> For the time being let's go the community route. If you are ready, we can announce on Reddit and Discord

Works for me!

**Comment by xloem** [comment]
@DavidVorick reviewing your position on third-party apis, it looks like the showstopper for inclusion of an api that can meet current feature parity and gives you control of their repository, would be finding somebody to provide ongoing maintenance to provide future feature parity.  Is this true?

I'm thinking of the issue of trusting third-party developers to stay as maintainers and it seems hard, but it seems providing for more apis would be very helpful for skynet.  Would it be reasonable to plan to rescind support for apis if a third-party maintainer leaves?

**Pull request closed without merging**
