### PR TITLE
Added skynet cache to nginx config, #214 fix

### LINKED ISSUE #214: Nginx proxy_cache zone "skynet" is unknown
The nginx config features a cache that has not been configured, thus nginx throws "unknown zone"
https://github.com/NebulousLabs/skynet-webportal/blob/468d2b036e768f7f64cc7e288dedc6062ec6eca9/setup-scripts/skynet-nginx.conf#L117

### PR DESCRIPTION
**Pull request by Delivator**
Should fix #214

### CODE REVIEW

**Comment by DaWe35** [comment]
I think we also need to add
```
sudo mkdir /data
sudo mkdir /data/nginx
sudo mkdir /data/nginx/cache
```
to setup.sh

**Comment by Delivator** [comment]
Woops got an typto, /tmp/ instead of /temp/

**Comment by marcinja** [comment]
Thanks for catching this.

On `siasky.net` we actually are using:
```
proxy_cache_path /tmp/nginx levels=1:2 keys_zone=skynet:10m max_size=10g inactive=24h use_temp_path=off;
```

I think we grabbed that from https://www.nginx.com/blog/nginx-caching-guide/ which has some justification.

**Comment by Delivator** [comment]
I mean max_size is up to the user, isn't it?
levels=1:2 and use_temp_path=off are probably a good idea, ill add these.

**Comment by Delivator** [comment]
Should be ready to be merged

**Comment by kwypchlo** [comment]
Thanks for the contribution @Delivator !

**Pull request merged**
